### PR TITLE
Change give it a try list items and request output element…

### LINKED ISSUE #47: Example list items in "Give it a try" should be links
… so we can easily copy the link URL, open it in a new tab, and even try it w/o JavaScript enabled. In browsers that support and allow JS, you can just `preventDefault()` to keep the old effect. Same for the URL shown in the "Request" box above.

### PR DESCRIPTION
**Pull request by nandhae**
**What it does:**
Closes #47 
**Description**
I have wrapped the "Give it a try" list items and the request output element with an anchor tag and put the urls into href dynamically and on click. It does change the style and add an underline to those items. Would be happy to remove that style and raise a PR if needed. Thanks.

### CODE REVIEW

**Comment by mk-pmb** [comment]
Thanks! At first I wondered why you wouldn't link to your PR in theissue thread. Then I remembered Github does it automatically, if you use one of the standard annotations. ;-) Try dropping the "[CLOSES ISSUE#47]" from the commit subject, you can use that space much better for the continued part. Instead, put it in the description as "Closes #47" in a line by itself. Meanwhile I'll try install and try your branch.

**Comment by nandhae** [comment]
@mk-pmb Thanks for that info. I'm a newbie when it comes to OSS contribution. That helps. Review it and lemme know what else can be done.

**Comment by mk-pmb** [comment]
Hi, sorry for the long delay. I managed to install it and it works as expected, thanks! Could you remove the link underlines, though? I think it looks more elegant without them, and I don't see an advantage to the user from having them.

**Comment by nandhae** [comment]
Sure @mk-pmb . I wanted to check with you on the underlines part as well. I'll put in a fix for that ASAP.

**Comment by nandhae** [comment]
@mk-pmb I have removed the underline style for the links. You can check and lemme know if there are any other changes needed.

**Comment by mk-pmb** [comment]
That's a huge lot of DOM changes. Why not just add a CSS rule `#console a { text-decoration: none; }`?

**Comment by nandhae** [comment]
That will be at an app level. That's why I have put the style specific to whatever tags I have added. If you think it's okay to have it at an app level, I would. But the specificity would help when people extend the app.

**Comment by mk-pmb** [comment]
If you think people might use `#console` in their extended app for sth. other, you could add a class to `#console` and use a selector like `#console.try-api-links a { text-decoration: none; }`

**Comment by nandhae** [comment]
Perfect, Would go with that suggestion then. Thanks.

**Comment by nandhae** [comment]
@mk-pmb I have made the appropriate changes. 👍

**Comment by mk-pmb** [comment]
Nice! The files look good to me now, but I'd rewrite history so it's just master + 1 clean new commit, with a commit style that matches the existing commits in master. To me that looks like subject should be just a concise description, any meta data (e.g. the "Fixes …" line) in the commit message only.

**Comment by mk-pmb** [comment]
Sorry for the too-early approval. I meant the changes looked good, but when I compare to master, there seems to be a lot of bloat still because some lines have exploded into multiple lines. All the more a reason to combine them into one new commit and make that one pretty.

**Comment by mk-pmb** [comment]
Also you introduced a new function that iterates over `;[].forEach.call(endpointEls,`, couldn't that be merged with the function below, that sets up the click listener?

I'd have loved to refer to those functions by name instead of that cryptic description. Onlookers, take this as example for why to always name your functions!

**Comment by nandhae** [comment]
Ok I'll merge them then. and yes i was having concerns about the method names too, but simply followed the existing ones. I'd change them too. After the changes, I'll add a commit and I'd be happy if you can merge them into a single commit.

**Comment by mk-pmb** [comment]
I don't have permission to modify your branch, so you'll have to squash the commits yourself. One easy way to do it is to
1. make a backup of the current branch (`git branch xyz-backup`)
1. do a soft reset (`git reset --soft master`; it will reset just history but keep any changes in files.)
1. then make the clean commit.

**Comment by nandhae** [comment]
Perfect, thanks. I'll squash and make a pretty commit after the changes myself then.

**Pull request merged**
